import Head from 'next/head'
import Image from 'next/image'
import { Button, Input, Select } from 'antd'

import Header from '../../components/Header'
import Footer from '../../components/Footer'
import ToolsTitle, { SmallToolsTitle } from '../../components/ToolsTitle'

import style from './index.module.scss'

const { Option } = Select;

export default function WalletQuery() {

  return (
    <>
      {/* 对于html 头部 */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 内容 */}
      <main className='page_tools_bj'>
        {/* 页面头部 */}
        <Header />

        <div className="container">
          <div className={style.wallet_query_authorization}>

            {/* 页面大小标题 */}
            <ToolsTitle title="Wallet Authorisation Search" />
            <SmallToolsTitle title="Check which contracts have been authorised at your wallet address and cancel expired or untrusted authorisations in time to keep your wallet safe!" />

            <div className="wallet_query">
              <div className='authorization_query'>

                <Select
                  dropdownClassName={style.select_dropdown}
                  defaultValue="ETH"
                  showArrow={false}
                >
                  <Option value="ETH">
                    <Image src='/svg/icon-3.svg' width={16} height={16} alt="" />
                    <span>ETH</span>
                  </Option>
                  <Option value="Heco">
                    <Image src='/svg/icon-2.svg' width={16} height={16} alt="" />
                    <span>Heco</span>
                  </Option>
                  <Option value="FTM">
                    <Image src='/svg/icon-1.svg' width={16} height={16} alt="" />
                    <span>FTM</span>
                    </Option>
                </Select>

                <Input placeholder='Please enter your wallet address to search'></Input>

                <Button type="primary" shape="round">Enquiry</Button>
              </div>

              <div className="hint">Very secure! The current wallet address is not authorized for any contract!</div>

              {/* 授权结果 */}
              <Authorization />
            </div>

          </div>
        </div>
      </main>

      {/* 底部 */}
      <footer>
        <Footer />
      </footer>
    </>
  )
}

function Authorization() {
  return (
    <div className="query_result">
      <div className="wallet_hint">
        <Image src='/svg/hint.svg' width={16} height={20} alt="" />
        <p>
          CoinSky only provides query function, it is not associated with your wallet in any way, to cancel authorization please do it yourself in your wallet!
        </p>
      </div>

      <div className="authorized_list">
        <div className="item">

          <div className="item_header">
            <div className="user_info">
              <Image src='/svg/icon-3.svg' width={30} height={30} alt="" />
              <div className="user_name">PancakeSwap Token</div>
            </div>
            <div className="pisks_success">Risks: High</div>
          </div>

          <div className="item_content">
            <div className='content'>
              Authorized Contracts: <span className='contracts'>0xa80240Eb5…891d00b51CC</span>
            </div>
            <div className='content'>
              Authorized Token: <span className='token'>0xa80240Eb5…891d00b51CC</span>
            </div>
            <div className='content'>
              Authorized Date: <span>02021-12-09 17:57:59(UTC)</span>
            </div>
            <div className='content'>
              Authorized Number: <span>Infinite Cake</span>
            </div>
          </div>
        </div>
        <div className="item">

          <div className="item_header">
            <div className="user_info">
              <Image src='/svg/icon-1.svg' width={30} height={30} alt="" />
              <div className="user_name">PancakeSwap Token</div>
            </div>
            <div className="pisks_error">Risks: Low</div>
          </div>

          <div className="item_content">
            <div className='content'>
              Authorized Contracts: <span className='contracts'>0xa80240Eb5…891d00b51CC</span>
            </div>
            <div className='content'>
              Authorized Token: <span className='token'>0xa80240Eb5…891d00b51CC</span>
            </div>
            <div className='content'>
              Authorized Date: <span>02021-12-09 17:57:59(UTC)</span>
            </div>
            <div className='content'>
              Authorized Number: <span>Infinite Cake</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
