import { Table } from 'antd'
import Head from 'next/head'
import Image from 'next/image'

import Footer from '../../components/Footer'
import Header from '../../components/Header'
import Title from '../../components/PageTitle'

import style from './index.module.scss'

export default function Exchange() {

  const columns = [
    {
      key: 'name',
      title: 'Name',
      width: '200px',
      dataIndex: 'name',
      className: 'exchange_name',
      render: (name) => {
        return (
          <>
            <Image src="/svg/icon-1.svg" width={20} height={20} alt="" />
            <a>{name}</a>
          </>
        )
      }
    },
    {
      width: '210px',
      key: 'arrivalTime',
      title: 'New Arrival Time',
      dataIndex: 'arrivalTime',
    },
    {
      width: '230px',
      key: 'platform',
      title: 'New Platform',
      dataIndex: 'platform',
    },
    {
      key: 'price',
      title: 'Price',
      width: '200px',
      dataIndex: 'price',
    },
    {
      width: '180px',
      key: 'increase',
      title: 'Increase',
      dataIndex: 'increase',
      render: increase => <span className={increase > 0 ? 'rise' : 'fall'}>{increase}%</span>,
    },
    {
      title: '',
      align: 'right',
      key: 'bulletin',
      dataIndex: 'bulletin',
      className: 'exchange_bulletin'
    },
  ];

  const data = [
    {
      key: '1',
      name: 'CELO',
      arrivalTime: '03.15 09:00:05',
      platform: 'Coinbase Exchange',
      price: '$0.0000000543',
      increase: '-4.43',
      bulletin: 'View the bulletin'
    },
    {
      key: '2',
      name: 'ZIMU',
      arrivalTime: '03.15 09:00:05',
      platform: 'MEXC',
      price: '$0.0000000543',
      increase: '103.43',
      bulletin: 'View the bulletin'
    },
    {
      key: '3',
      name: 'SD',
      arrivalTime: '03.15 09:00:05',
      platform: 'Huobi Global',
      price: '$0.000842',
      increase: '103.43',
      bulletin: 'View the bulletin'
    },
  ];

  return (
    <>
      {/* 对于html 头部 */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 内容 */}
      <main className='page_tools_bj'>
        {/* 页面头部内容 */}
        <Header></Header>

        <div className="container">

          <div className={style.exchange}>
            <Title title="New on the Exchange" />

            <div className="prompt">
              Download the app to subscribe to notifications of new releases on each exchange,&nbsp;
              <span>Subscribe now</span>!
            </div>

            {/* 表格部分数据 */}
            <Table columns={columns} dataSource={data} pagination={false} />
          </div>

        </div>
      </main>

      {/* 底部 */}
      <footer>
        <Footer />
      </footer>
    </>
  )
}
