import { Table } from 'antd'
import Head from 'next/head'
import Image from 'next/image'

import Footer from '../../components/Footer'
import Header from '../../components/Header'
import ToolsTitle from '../../components/ToolsTitle'
import { getTime } from '../../utils/date'
import Request from '../../utils/fetch'

import style from './index.module.scss'

export default function Exchange({ getNewCoins }) {
  console.log(getNewCoins);

  const columns = [
    {
      key: 'name',
      title: 'Name',
      width: '200px',
      dataIndex: 'name',
      className: 'exchange_name',
      render: (name, record) => {
        return (
        <>
          <Image src="/svg/icon-1.svg" width={20} height={20} alt="" />
          <a>{name}</a>
        </>
        )
      }
    },
    {
      width: '210px',
      key: 'time',
      title: 'New Arrival Time',
      dataIndex: 'time',
      render: time => (
        <span style={ {color: '#14161A', fontWeight: '400',fontFamily: 'PingFangSC-Regular, PingFang SC'} }>{ getTime(time) }</span>
      )
    },
    {
      width: '230px',
      key: 'exchange',
      title: 'New Platform',
      dataIndex: 'exchange',
    },
    {
      key: 'price',
      title: 'Price',
      width: '200px',
      dataIndex: 'price',
      render: price => (
        <span>{ price ? `$${price}` : '-' }</span>
      )
    },
    {
      width: '180px',
      key: 'rate_24h',
      title: 'Increase',
      dataIndex: 'rate_24h',
      render: increase => <span className={increase > 0 ? 'rise' : 'fall'}>{increase ? `${increase}%` : '-'}</span>,
    },
    // {
    //   title: '',
    //   align: 'right',
    //   key: 'bulletin',
    //   dataIndex: 'bulletin',
    //   className: 'exchange_bulletin'
    // },
  ];

  const data = [...getNewCoins];

  return (
    <>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className='page_tools_bj'>
        
        <Header></Header>

        <div className="container">

          <div className={style.exchange}>
            <ToolsTitle title="New on the Exchange" />

            <div className="prompt">
              Download the app to subscribe to notifications of new releases on each exchange,&nbsp;
              <a target="_blank" href='https://www.coinsky.ai/' rel="noreferrer">Subscribe now</a>!
            </div>

            {/* 表格部分数据 */}
            <Table columns={columns} dataSource={data} pagination={false} />
          </div>

        </div>
      </main>

      
      <footer>
        <Footer />
      </footer>
    </>
  )
}
export async function getServerSideProps(context) {
  const getNewCoins = await Request('/newCoins.json')
  return {
    props: { getNewCoins }
  }
}