import React from "react";
import Head from 'next/head'
import Footer from '../../components/Footer'

import Header from '../../components/Header'
import ToolsTitle from '../../components/ToolsTitle'
import Request from '../../utils/fetch'

import style from './curriculumDetail.module.scss'

export default function CurriculumDetail({ articleDetail }) {

  return (
    <>
      {/* 对于html 头部 */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 内容 */}
      <main className='page_tools_bj'>
        {/* 页面头部内容 */}
        <Header></Header>

        {/* 页面详情内容 */}
        <div className="container">
          <div className={style.detail}>
            <ToolsTitle bottom='26px' title="Blockchain White Book" />

            <div className="article">
              <div className="article_title">{articleDetail.title}</div>
              <div className="article_content" dangerouslySetInnerHTML={{ __html: articleDetail.content }} />
            </div>
          </div>
        </div>
      </main>

      {/* 底部 */}
      <footer>
        <Footer />
      </footer>
    </>
  )
}

export async function getServerSideProps(context) {

  // 获取课堂详情数据
  const articleDetail = await Request('/h5/getArticleDetails.json', {
    body: {
      ctx_id: context.query.ctx_id
    }
  })

  // html 反转义
  const escapeHtml = (str) => {
    var arrEntities = { 'lt': '<', 'gt': '>', 'amp': '&', 'quot': '"' };
    let htmlTag = str.replace(/&(lt|gt|amp|quot);/ig, function (all, t) {
      return arrEntities[t];
    });
    return htmlTag
  }

  articleDetail.content = escapeHtml(articleDetail.content)

  return {
    props: {
      articleDetail: articleDetail
    }
  }
}
