import Head from 'next/head'
import Footer from '../../components/Footer'

import Header from '../../components/Header'
import ToolsTitle from '../../components/ToolsTitle'

import style from './curriculumDetail.module.scss'

export default function curriculumDetail() {
  return (
    <>
      {/* 对于html 头部 */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 内容 */}
      <main className='page_tools_bj'>
        {/* 页面头部内容 */}
        <Header></Header>

        {/* 页面详情内容 */}
        <div className="container">
          <div className={style.detail}>
            <ToolsTitle bottom='26px' title="Blockchain White Book" />

            <div className="article">
              <div className="article_title">How to DeFi</div>
              <div className="article_content">
                When we first wrote the book How to Use DeFi: For Beginners (First Edition) in March 2020, we intentionally omitted a lot of information to make it easier for beginners to get started with DeFi. we knew that the book was only scratching the surface of what DeFi has to offer. Of course, it doesn t seem that way to beginners - many just want to learn about a fast-growing industry that is known for its steep learning curve.<br />
                <div style={{ height: '8px' }}></div>
                As our readers began to familiarise themselves with the basics of DeFi, the need for more in-depth knowledge soon followed. We knew we needed to write a follow-up report for readers interested in exploring DeFi further, so we wrote this advanced book to serve that purpose.<br />
                <div style={{ height: '8px' }}></div>
                We cannot underestimate how easy it is to get lost in DeFi. Every week new protocol innovations emerge that make DeFi more effective and further expand the usage scenarios. Completely addressing this knowledge gap is impossible. However, we hope to bridge this gap with our research and analysis of key parts of DeFi in this book.
                In this book, we will provide an update on the state of DeFi and what we can expect in the future.
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* 底部 */}
      <footer>
        <Footer />
      </footer>
    </>
  )
}
