import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'

import Header from '../../components/Header'
import Footer from '../../components/Footer'
import ToolsTitle, { SmallToolsTitle } from '../../components/ToolsTitle'

import style from './index.module.scss'
import Request from '../../utils/fetch'

export default function NewCurriculum({ getDirectoryList }) {
  const router = useRouter()

  // 去详情页
  const toDetail = (ctx_id) => {
    router.push({
      pathname: `/newCurriculum/${ctx_id}`
    })
  }

  return (
    <>
      {/* 对于html 头部 */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 内容 */}
      <main className='page_tools_bj'>
        {/* 页面头部内容 */}
        <Header></Header>

        {/* 页面内容 */}
        <div className="container">

          <div className={style.class}>
            <ToolsTitle title="Beginner’s Guide" bottom='-4px' />

            {getDirectoryList.map((item) => (
              <div className="class_list" key={item.classify_id}>
                <div className='title'>{item.name}</div>

                {item.articles.map((sonItem) => (
                  <div className="class_item" key={sonItem.ctx_id} onClick={() => toDetail(sonItem.ctx_id)}>
                    <div className="class_name">{sonItem.title}</div>
                    <Image src="/svg/right_pages.svg" width={8} height={14} alt="" />
                  </div>
                ))}
              </div>
            ))}
          </div>
        </div>
      </main>

      {/* 底部 */}
      <footer>
        <Footer />
      </footer>
    </>
  )
}

export async function getServerSideProps(context) {
  const getDirectoryList = await Request('/h5/getDirectoryList.json', {
    body: {
      lang: 'EN',
      client: 'wap'
    }
  })

  return {
    props: {
      getDirectoryList
    }
  }
}