import { Table, Tabs } from 'antd'
import { useState } from 'react'
import Image from 'next/image'
import Head from 'next/head'

import Footer from '../../components/Footer'
import Header from '../../components/Header'
import ToolsTitle from '../../components/ToolsTitle'

import style from './index.module.scss'

export default function StableFinancial() {

  const { TabPane } = Tabs;
  const [tabs] = useState(['Binance', 'OKX'])

  const callback = (key) => {
    console.log(key);
  }

  const columns = [
    {
      width: '210px',
      title: 'Popular Coins',
      dataIndex: 'name',
      className: 'popular_coins',
      render: (name) => (
        <>
          <Image src="/svg/icon-1.svg" width={20} height={20} alt="" />
          <a>{name}</a>
        </>
      )
    },
    {
      width: '240px',
      title: 'New Platform',
      dataIndex: 'platform',
    },
    {
      width: '240px',
      title: 'Annual yield',
      dataIndex: 'annual',
      sorter: {
        compare: (a, b) => a.annual - b.annual,
      },
      render: annual => <span className={annual > 0 ? 'rise' : 'fall'}>{annual}%</span>
    },
    {
      width: '220px',
      title: 'Deadline',
      dataIndex: 'deadline',
      sorter: {
        compare: (a, b) => a.deadline - b.deadline,
      },
    },
    {
      title: '',
      width: '190px',
      dataIndex: 'eamings',
      className: 'eamings'
    },
  ];

  const data = [
    {
      key: '1',
      name: 'CELO',
      platform: 'Staking',
      annual: '104.62',
      deadline: '90 days',
      eamings: 'Eamings'
    },
    {
      key: '2',
      name: 'AXS',
      platform: '币安宝定期',
      annual: '-3.56',
      deadline: '15 days',
      eamings: 'Eamings'
    },
    {
      key: '3',
      name: 'DOT',
      platform: 'Staking',
      annual: '50.62',
      deadline: '90 days',
      eamings: 'Eamings'
    },
    {
      key: '4',
      name: 'NEAR',
      platform: 'Staking',
      annual: '-4.43',
      deadline: '30 days',
      eamings: 'Eamings'
    },
  ];

  return (
    <>
      {/* 对于html 头部 */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 内容 */}
      <main className='page_tools_bj'>
        {/* 页面头部内容 */}
        <Header></Header>

        {/* 页面内容部分 */}
        <div className="container">
          <div className={style.stableFinancial}>
            <ToolsTitle title="Financial stability" />

            <div className="financial">
              <div className="title">Give a lazy way to manage your cryptocurrency money.</div>

              <Tabs defaultActiveKey="0" onChange={callback}>

                {tabs.map((item, index) => (
                  <TabPane tab={item} key={index}>

                    <Table
                      columns={columns}
                      dataSource={data}
                      pagination={false}
                      showSorterTooltip={false}
                    />

                  </TabPane>
                ))}

              </Tabs>

            </div>
          </div>
        </div>
      </main>

      {/* 底部 */}
      <footer>
        <Footer />
      </footer>
    </>
  )
}
