import Head from 'next/head'
import Header from '../../components/Header'
import Footer from '../../components/Footer'

export default function CurrencyConverter() {
  return (
    <>
      {/* 对于html 头部 */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 内容 */}
      <main className='page_tools_bj'>
        {/* 页面头部内容 */}
        <Header />

        <Footer />
      </main>
    </>
  )
}
